### ISSUE TITLE
使用idf 4.3/4.4 编译报错

### ISSUE THREAD

**Issue by liuaoalan** [blinker-iot/blinker-freertos#11]
使用 example 下的 Hello_WiFi 编译 ，报错如下 ， 好像头文件内容没有识别，idf 4.3/4.4 都有此问题
../components/Blinker/src/utils/blinker_ws.c: In function 'blinker_websocket_async_print':
../components/Blinker/src/utils/blinker_ws.c:62:5: error: unknown type name 'httpd_ws_frame_t'; did you mean 'httpd_work_fn_t'?
     httpd_ws_frame_t ws_pkt;
     ^~~~~~~~~~~~~~~~
     httpd_work_fn_t
../components/Blinker/src/utils/blinker_ws.c:63:31: error: 'httpd_ws_frame_t' undeclared (first use in this function); did you mean 'httpd_work_fn_t'?
     memset(&ws_pkt, 0, sizeof(httpd_ws_frame_t));
                               ^~~~~~~~~~~~~~~~
                               httpd_work_fn_t
../components/Blinker/src/utils/blinker_ws.c:63:31: note: each undeclared identifier is reported only once for each function it appears in
../components/Blinker/src/utils/blinker_ws.c:64:11: error: request for member 'payload' in something not a structure or union
     ws_pkt.payload = (uint8_t *)payload;
           ^
../components/Blinker/src/utils/blinker_ws.c:65:11: error: request for member 'len' in something not a structure or union
     ws_pkt.len     = strlen(payload);
           ^
../components/Blinker/src/utils/blinker_ws.c:66:11: error: request for member 'type' in something not a structure or union

**Comment by i3water** [comment]
按文档说明**将esp_http_server剪切并到sdk安装目录下的components内并覆盖原来的esp_http_server文件**

**Comment by liuaoalan** [comment]
> 
已经覆盖了，下面是覆盖后的 git 变化，环境是win10 ，版本是 idf  4.3.4
Not currently on any branch.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   esp_http_server/CMakeLists.txt
        modified:   esp_http_server/Kconfig
        modified:   esp_http_server/component.mk
        modified:   esp_http_server/include/esp_http_server.h
        modified:   esp_http_server/include/http_server.h
        modified:   esp_http_server/src/esp_httpd_priv.h
        modified:   esp_http_server/src/httpd_main.c
        modified:   esp_http_server/src/httpd_parse.c
        modified:   esp_http_server/src/httpd_sess.c
        modified:   esp_http_server/src/httpd_txrx.c
        modified:   esp_http_server/src/httpd_uri.c
        modified:   esp_http_server/src/httpd_ws.c
        modified:   esp_http_server/src/port/esp32/osal.h
        modified:   esp_http_server/src/util/ctrl_sock.c
        modified:   esp_http_server/src/util/ctrl_sock.h
        modified:   esp_http_server/test/CMakeLists.txt
        modified:   esp_http_server/test/component.mk
        modified:   esp_http_server/test/test_http_server.c

**Comment by i3water** [comment]
enable mDNS
disable Newlib
enable webSocket server support(http_server)

idf config设置开启websocket支持

**Comment by liuaoalan** [comment]
可以了 ，多谢
