### ISSUE TITLE
关于platformIO

### ISSUE THREAD

**Issue by LonelySally** [blinker-iot/blinker-freertos#6]
求问下能否更新下platformIO上的扩展版本,扩展拉下来太古老了全是错误提示.

**Comment by i3water** [comment]
抱歉platformIO上面的扩展不是我们维护更新的。

**Comment by LonelySally** [comment]
> 抱歉platformIO上面的扩展不是我们维护更新的。

扩展库指向的git地址是这个地方的,是否考虑官方维护该扩展(发布)? 我看Arduino论坛上也挺多人提到过platformIO的使用.

**Comment by LonelySally** [comment]
https://platformio.org/lib/show/2519/Blinker

![image](https://user-images.githubusercontent.com/26945597/127353512-c48e962c-0382-4481-abdf-6a6d86a7692a.png)

**Comment by coloz** [comment]
platformIO上应该是某个用户上传的，我们没用使用platformIO，且没有提交过lib，建议自己研究下怎么导入到platformIO。

**Comment by LonelySally** [comment]
> platformIO上应该是某个用户上传的，我们没用使用platformIO，且没有提交过lib，建议自己研究下怎么导入到platformIO。

手动把新的SDK替换的扩展目录里就能使用了.3Q.
