### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by cjkzwe** [blinker-iot/blinker-freertos#7]
In file included from ../components/Blinker/include/blinker_api.h:10,
                 from ../components/Blinker/src/api/blinker_api.c:13:
D:/ESP/ESP-IDF/components/json/cJSON/cJSON.h:269:22: note: expected 'cJSON * const' {aka 'struct cJSON * const'} but argument is of type 'const char *'
 CJSON_PUBLIC(cJSON*) cJSON_AddStringToObject(cJSON * const object, const char * const name, const char * const string);

**Comment by coloz** [comment]
ESP8266_RTOS_SDK v3.4
ESP_IDF v4.3
请确保版本匹配

**Comment by cjkzwe** [comment]
我的版本是对的，但是重装了好多次esp-idf依然不行,
./main/blinker_example_main.c: In function 'button1_callback':
../main/blinker_example_main.c:45:5: error: implicit declaration of function 'ESP_LOGI'; did you mean 'ESP_OK'? [-Werror=implicit-function-declaration]
     ESP_LOGI(TAG, "button state: %s", val->s);
     ^~~~~~~~
     ESP_OK
../main/blinker_example_main.c: In function 'app_main':
../main/blinker_example_main.c:71:50: error: 'button_callback' undeclared (first use in this function); did you mean 'button1_callback'?
     blinker_widget_add(BUTTON_1, BLINKER_BUTTON, button_callback);
                                                  ^~~~~~~~~~~~~~~
                                                  button1_callback
../main/blinker_example_main.c:71:50: note: each undeclared identifier is reported only once for each function it appears in
cc1.exe: some warnings being treated as errors
[928/934] Building C object esp-idf/Blinker/CMakeFiles/__idf_Blinker.dir/src/api/blinker_api.c.obj
../components/Blinker/src/api/blinker_api.c: In function 'blinker_va_print':
../components/Blinker/src/api/blinker_api.c:840:33: warning: passing argument 1 of 'cJSON_AddStringToObject' from incompatible pointer type [-Wincompatible-pointer-types]
         cJSON_AddStringToObject(param, BLINKER_CMD_MESSAGE_ID, from_param->message_id);
                                 ^~~~~
In file included from ../components/Blinker/include/blinker_api.h:10,
                 from ../components/Blinker/src/api/blinker_api.c:13:
D:/ESP/ESP-IDF/components/json/cJSON/cJSON.h:269:22: note: expected 'cJSON * const' {aka 'struct cJSON * const'} but argument is of type 'const char *'
 CJSON_PUBLIC(cJSON*) cJSON_AddStringToObject(cJSON * const object, const char * const name, const char * const string);
                      ^~~~~~~~~~~~~~~~~~~~~~~
../components/Blinker/src/api/blinker_api.c: In function 'blinker_device_mqtt_init':
../components/Blinker/src/api/blinker_api.c:2368:23: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
         pro_auth.uuid = blinker_mqtt_uuid();
                       ^
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by cjkzwe** [comment]
我的是esp32 wroom.

**Comment by i3water** [comment]
从报错看和库关系不大，感觉你的编译环境是否没有配置好？

**Comment by cjkzwe** [comment]
我查出原因来了，我是一直以为你们的example代码不会出错，但是实际上我在里面找到了几个错误，修复后编译成功了。
