### ISSUE TITLE
编译时警告incompatible pointer type

### ISSUE THREAD

**Issue by cjkzwe** [blinker-iot/blinker-freertos#8]
有以下警告，提示指针类型不对，不知道有没有影响
C:/Users/****/Desktop/hello_world/components/Blinker/src/api/blinker_api.c: In function 'blinker_va_print':
C:/Users/****/Desktop/hello_world/components/Blinker/src/api/blinker_api.c:840:33: warning: passing argument 1 of 'cJSON_AddStringToObject' from incompatible pointer type [-Wincompatible-pointer-types]
         cJSON_AddStringToObject(param, BLINKER_CMD_MESSAGE_ID, from_param->message_id);
                                 ^~~~~
In file included from C:/Users/cjfzw/Desktop/hello_world/components/Blinker/include/blinker_api.h:10,
                 from C:/Users/cjfzw/Desktop/hello_world/components/Blinker/src/api/blinker_api.c:13:
C:/Espressif/frameworks/esp-idf-v4.4/components/json/cJSON/cJSON.h:269:22: note: expected 'cJSON * const' {aka 'struct cJSON * const'} but argument is of type 'const char *'
 CJSON_PUBLIC(cJSON*) cJSON_AddStringToObject(cJSON * const object, const char * const name, const char * const string);
                      ^~~~~~~~~~~~~~~~~~~~~~~

环境:esp-idf-v4.4
Windows 10
Clion
MinGW

**Comment by i3water** [comment]
目前只支持idf 4.3，暂未对4.4进行测试，可能有不兼容情况。

**Comment by i3water** [comment]
现已支持v4.4 idf
